## 4: FUNCTIONS FOR ITEMS PER TIME, STORENAME

### Import libraries

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
from random import sample
class bcolors:
    WARNING = '\033[91m'
    BOLD = '\033[1m'

### Load and view data

In [6]:
    # Function to generate #visits per day of the week
from AlgorithmDAYS_HH2 import beforeNY, AfterNY, daysAfterNY
    #Function to define the limits for total visits, days, same store and type per week
from AlgorithmCOUNTS_HH2 import CountTotalVisits, CountTotalDays, CountStoreName, CountStoreType, CountTotalPerday, CountVisitsPerDay
    # Function to generate #visits per time
from AlgorithmTIMES_HH2 import AlbertHeijn, Okay, Delhaize, Carrefour, VersavelPoelman, Sys, Brabo, Ikea, Kruidvat
    # Function to decide amounts per visit & per week
from AlgorithmAMOUNT_HH2 import StoreAmount, WeekAmount, StoreCount, WeekCount, CatCount, PerCatCount, PerCatCountALL, PerCatCountSTORE, PerCatCountSTORE
    # Function to generate store name (&type) per weekday (+ assign #of visits per day)
from AlgorithmSTORE_HH2 import storeperday, countsperstore

In [7]:
dataframe = pd.read_csv (r"C:\Users\20204113\OneDrive - TU Eindhoven\2_Research\1_Groceries\DATA\9th week - narrative (3rd attempt)\HH2\df\df_HH2.csv")

# Get counts per store etc

In [9]:
CountStoreType('supermarket')

(1, 5)

In [10]:
CountStoreName('Albert Heijn')

(0, 5)

In [11]:
df1 = daysAfterNY(dataframe)

df2 = storeperday(df1)

df3 = countsperstore(df2)
df3['I'] = np.arange(df3.shape[0])
df3

 RERUN - Too few/many visits per week
 RERUN - Too few/many visits per week
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: butcher
 RERUN - Too many store name: Versavel Poelman
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: supermarket
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: supermarket
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: supermarket
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: drugstore
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: butcher
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: supermarket
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: supermarket
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: supermarket
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: butcher
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: butcher
 RERUN - Too many store name: Versavel Poelman
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday
 RERUN - Too few store type: supermarket
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: bakery
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday
 RERUN - Too many store type: supermarket
 RERUN - Too many store name: Okay
 RERUN - Too many stores on: Tuesday
 RERUN - Too few store type: supermarket
 RERUN - Too many store name: Sys
 RERUN - Too many stores on: Tuesday

         store_name   store_type       day       time  counts  I
0              Okay  supermarket   Tuesday  afternoon      11  0
1          Kruidvat    drugstore   Tuesday  afternoon       3  1
2      Albert Heijn  supermarket  Thursday    morning       3  2
3         Carrefour  supermarket  Saturday  afternoon      31  3
4               Sys       bakery  Saturday    morning       5  4
5  Versavel Poelman      butcher  Saturday    morning       7  5

# DEFINE FUNCTIONS

In [12]:
data = {'store_name': ['Albert Heijn', 'Sys', 'Okay', 'Versavel Poelman'],
       'store_type': ['supermarket', 'bakery', 'supermarket', 'butcher'],
        'day': ['Thursday', 'Saturday', 'Saturday', 'Saturday'],
       'time': ['noon', 'noon', 'afternoon', 'morning'],
       'counts': [3, 5, 35, 7],}
df4 = pd.DataFrame(data)
df4['I'] = np.arange(df4.shape[0])
df4

         store_name   store_type       day       time  counts  I
0      Albert Heijn  supermarket  Thursday       noon       3  0
1               Sys       bakery  Saturday       noon       5  1
2              Okay  supermarket  Saturday  afternoon      35  2
3  Versavel Poelman      butcher  Saturday    morning       7  3

### Split up the dataframe per store type

In [15]:
def supermarket(dataframes, counts, storenamez):
        ## Create dataframes for each day they go shopping
    typedf = {}
    storetypes = dataframes.store_type.values.tolist()
    storename = dataframes.store_name.values.tolist()           
    thisdaysdf = {}
    daydf = {}
    for storetype in dataframes['store_type']:
            storeday = df[df['store_type'] == storetype]
            items = storeday[['item_type', 'item_name', 'time', 'store_type','store_name', 'amount', 'category', 'weights_itemtype']]
            typedf[storetype] = pd.DataFrame(items)
            typedf[storetype].drop_duplicates()        
    ## Split up the dataframes to store name for certain times
    if 'supermarket'in dataframes.values:
            for time in storename:
                thisdaydf = typedf['supermarket']
                storesdf = thisdaydf[thisdaydf['store_name'] == time]
                items = storesdf[['item_type', 'item_name', 'store_type', 'store_name', 'amount', 'category', 'weights_itemtype']]
                daydf[time] = pd.DataFrame(items)
                daydf[time].drop_duplicates()                
    ## Sample the dataframes per store type they go shopping
    if 'supermarket' in dataframes.values:
            grocerylist = dataframes[dataframes['store_type'] == 'supermarket']
            if 'supermarket' in dataframes.values:
                daydf[storenamez]= daydf[storenamez].drop_duplicates()
                return daydf[storenamez].sample(n=counts, replace=False)

In [16]:
supermarket(df3, 5, 'Okay')

,item_type,item_name,store_type,store_name,amount,category,weights_itemtype
83,vegetable mix,FLORETTE groentenmix Bordje Krokant 250g,supermarket,Okay,1,fruit & vegetables,3
106,coconut drink,ALPRO kokosnootdrink 1L,supermarket,Okay,1,dairy & plant based,1
98,cereal,KELLOGG'S TRéSOR choco-hazelnoot 450g,supermarket,Okay,1,breakfast & spreads,2
77,pasta sauce,SPAGHERONI pastasaus tradizionale 520g,supermarket,Okay,1,condiments,1
110,ice tea,BONI Green Tea niet-bruisend 33cl,supermarket,Okay,6,beverages,4

In [26]:
def butcher(dataframes, counts):
        ## Create dataframes for each day they go shopping
    typedf = {}
    for storetype in dataframes['store_type']:
            storeday = df[df['store_type'] == storetype]
            items = storeday[['item_type', 'item_name', 'store_type','store_name', 'amount', 'category', 'weights_itemtype']]
            typedf[storetype] = pd.DataFrame(items)
            typedf[storetype].drop_duplicates() 
        ## sample dataframes per store type
    if 'butcher' in dataframes.values:
            grocerylist = dataframes[dataframes['store_type'] == 'butcher']
            if 'butcher' in dataframes.values:
                typedf['butcher'] = typedf['butcher'].drop_duplicates()
                return typedf['butcher'].sample(n=counts, replace=False)

In [18]:
def bakery(dataframes, counts):
        ## Create dataframes for each day they go shopping
    typedf = {}
    for storetype in dataframes['store_type']:
            storeday = df[df['store_type'] == storetype]
            items = storeday[['item_type', 'item_name', 'store_type','store_name', 'amount', 'category', 'weights_itemtype']]
            typedf[storetype] = pd.DataFrame(items)
            typedf[storetype].drop_duplicates() 
    if 'bakery' in dataframes.values:
        grocerylist = dataframes[dataframes['store_type'] == 'bakery']
        if 'bakery' in dataframes.values:
            typedf['bakery'] = typedf['bakery'].drop_duplicates()
            return typedf['bakery'].sample(n=counts, replace=False)

In [20]:
bakery(df3, 3)

,item_type,item_name,store_type,store_name,amount,category,weights_itemtype
5,bread,KLEIN GROF GESN.,bakery,Sys,1,bakery,16
294,danish,CHOCOLADE CRÈME KOEK,bakery,Sys,4,bakery,9
129,danish,RONDE BOTERKOEK,bakery,Sys,1,bakery,9

In [28]:
def drugstore(dataframes, counts):
        ## Create dataframes for each day they go shopping
    typedf = {}
    for storetype in dataframes['store_type']:
            storeday = df[df['store_type'] == storetype]
            items = storeday[['item_type', 'item_name', 'store_type','store_name', 'amount', 'category', 'weights_itemtype']]
            typedf[storetype] = pd.DataFrame(items)
            typedf[storetype].drop_duplicates() 
    if 'drugstore' in dataframes.values:
            grocerylist = dataframes[dataframes['store_type'] == 'drugstore']
            if 'drugstore' in dataframes.values:
                typedf['drugstore'] = typedf['drugstore'].drop_duplicates()
                return typedf['drugstore'].sample(n=counts, replace=False)

In [29]:
def furniturestore(dataframes, counts):
        ## Create dataframes for each day they go shopping
    typedf = {}
    for storetype in dataframes['store_type']:
            storeday = df[df['store_type'] == storetype]
            items = storeday[['item_type', 'item_name', 'store_type','store_name', 'amount', 'category', 'weights_itemtype']]
            typedf[storetype] = pd.DataFrame(items)
            typedf[storetype].drop_duplicates() 
    if 'furniture store' in dataframes.values:
            grocerylist = dataframes[dataframes['store_type'] == 'furniture store']
            if 'furniture store' in dataframes.values:
                daydf['furniture store'] = daydf['furniture store'].drop_duplicates()
                return daydf['furniture store'].sample(n=counts, replace=False)

### Get lists per store type for the weekplanning output

In [33]:
def supermarkets(dataframes, index):
    storesuper = dataframes[dataframes['store_type'] == 'supermarket']
    storesuper = storesuper[['time', 'store_type', 'counts', 'I']]
    storesuper = storesuper.to_numpy()
    s = {}
    supermarkets = pd.DataFrame(columns = ['item_type', 'item_name', 'amount', 'category'])
    for timing, storetype, counts, i in storesuper:
        s[i] = pd.DataFrame(supermarket(dataframes, counts, timing))     
    s[i] = s[index]
    return s[index]

In [34]:
supermarkets(df4, 0)

,item_type,item_name,store_type,store_name,amount,category,weights_itemtype
228,lunch salad,VERSE PASTA,supermarket,Albert Heijn,1,fruit & vegetables,9
232,lunch salad,AH MLTSALADE,supermarket,Albert Heijn,1,fruit & vegetables,9
118,lunch,WRAP KIP,supermarket,Albert Heijn,1,"meat, fish & veggie",3

In [36]:
def bakeries(dataframes, index):
    storebake = dataframes[dataframes['store_type'] == 'bakery']
    storebake = storebake[['store_type', 'counts', 'I']]
    storebake = storebake.to_numpy()
    ba = {}
    supermarkets = pd.DataFrame(columns = ['item_type', 'item_name', 'amount', 'category'])
    for storetype, counts, i in storebake:
        ba[i] = pd.DataFrame(bakery(dataframes, counts))     
    ba[i] = ba[index]
    return ba[index]

In [40]:
def butchers(dataframes, index):
    #butcher
    storebutch = dataframes[dataframes['store_type'] == 'butcher']
    storebutch = storebutch[['store_type', 'counts', 'I']]
    storebutch = storebutch.to_numpy()
    bu = {}
    butchers = pd.DataFrame(columns = ['item_type', 'item_name', 'amount', 'category'])
    for storetype, counts, i  in storebutch:
        if storetype == 'butcher':
            bu[i] = pd.DataFrame(butcher(dataframes, counts))
    return bu[index]

In [26]:
def drugstores(dataframes, index):
    #drugstore
    storedrug = dataframes[dataframes['store_type'] == 'drugstore']
    storedrug = storedrug[['store_type', 'counts', 'I']]
    storedrug = storedrug.to_numpy()
    d = {}
    drugstores = pd.DataFrame(columns = ['item_type', 'item_name', 'amount', 'category'])
    for storetype, counts, i  in storedrug:
        if storetype == 'butcher':
            d[i] = pd.DataFrame(drugstore(dataframes, counts))
    return d[index]

In [27]:
def furnstores(dataframes, index):
        #furniture store
    storefurn = dataframes[dataframes['store_type'] == 'furniture store']
    storefurn = storefurn[['store_type', 'counts', 'I']]
    storefurn = storefurn.to_numpy()
    f = {}
    furnstores = pd.DataFrame(columns = ['item_type', 'item_name', 'amount', 'category'])
    for storetype, counts, i  in storefurn:
        if storetype == 'butcher':
            f[i] = pd.DataFrame(furniturestore(dataframes, counts))
    return f[index]